### ISSUE TITLE
Deploy a production level Kafka and Zookeeper

### ISSUE THREAD

**Issue by tilleryd** [greymatter-io/helm-charts#233]
We're going to deploy Kafka and Zookeeper to support observables for the core Grey Matter services.

**Comment by chrisbsmith** [comment]
The zookeeper/kafka infrastructure is not a core component of Grey Matter, and we offer a solution to deploy a zookeeper/kafka cluster for observables in the [observables](https://github.com/greymatter-io/helm-charts/observables) folder. Closing
