### ISSUE TITLE
Helm chart releases are not well defined.

### ISSUE THREAD

**Issue by joshua-rutherford** [greymatter-io/helm-charts#261]
Currently the pipeline pushes all commits to a `release-*` branches to the chart repository in Nexus.  This means that un-tagged version will be pushed as whatever the current version in the `Chart.yaml` file says.   Since there is no concept of `-SNAPSHOT` or `-dev` in this version file this results in intermediate versions being pushed as what appears to be released versions.

Suggest we only push tagged releases to Nexus.

**Comment by chrisbsmith** [comment]
I believe between the new linting checks and the automated release function, we can close this issue.
