### ISSUE TITLE
mongo db data path should be configurable

### ISSUE THREAD

**Issue by dgoldstein1** [greymatter-io/helm-charts#312]
- Currently mongo db persistent datapath is tied to `/data/db`, which is the default for mongo, however this could change from deployment to deployment

**Comment by chrisbsmith** [comment]
This is now configurable: https://github.com/greymatter-io/helm-charts/blob/d3eb10cdfbfc302570934852c51eb41a67f232d3/data/gm-data/values.yaml#L189
