### ISSUE TITLE
Clean up image versions

### ISSUE THREAD

**Issue by kaitmore** [greymatter-io/helm-charts#339]
From @chrisbsmith :

On a side note, I think we need an issue to update our greymatter.yaml to change how we update the image versions. Looking at the /values.yaml, images are defined as

https://github.com/DecipherNow/helm-charts/blob/60b1fcd7bc5ee949717f7f749e17edc95a3b4a76/control/values.yaml#L22

```
image: 'docker.production.deciphernow.com/deciphernow/gm-control:{{$.Values.global.control.version }}
```
For control (and hopefully the others) we should only need to update > $.Values.global.control.version (and similar for other services). This should allow us to only update versions in a single place instead of throughout.

**Comment by chrisbsmith** [comment]
closing as stale
