### ISSUE TITLE
Proposal: new automated ways to test the Helm Charts

### ISSUE THREAD

**Issue by chrisbsmith** [greymatter-io/helm-charts#443]
The Helm Charts need additional testing.  This proposal should recommend new ways to automate testing of the Grey Matter helm charts.

These are some ideas for testing:

* using circle ci to spin up a minikube and deploy Grey Matter to it, then run GM Integrity
* use circle ci to spin up an EC2 instance in our AWS account to do the same as ^

**Comment by tilleryd** [comment]
Related https://github.com/DecipherNow/helm-charts/issues/365

**Comment by whenhellfreezes** [comment]
https://github.com/kubernetes-sigs/kind . I am interested in using KinD for this purpose. I have tried helm install but KinD was unable to create PVs to actually allow me to test greymatter.

**Comment by chrisbsmith** [comment]
This has been closed to #770
