### ISSUE TITLE
Update ci to use yaml anchors to remove redundant code

### ISSUE THREAD

**Issue by moosecanswim** [greymatter-io/helm-charts#638]
Use yaml anchors to remove redundant code... also makes it so we would only need to make changes in one place instead of duplicating code across the stages

https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/

**Comment by chrisbsmith** [comment]
As we being migrating away from CircielCi to GitHub Actions, I feel we can close this issue.
