### ISSUE TITLE
Upgrade Grey Matter Proxy to 1.4.5

### ISSUE THREAD

**Issue by chrisbsmith** [greymatter-io/helm-charts#734]
Grey Matter Proxy was released and the Helm Charts need to deploy it out of the box

New image is `docker.greymatter.io/development/gm-proxy:1.4.5`

**Comment by zakilur** [comment]
Helm Charts are already using image `docker.greymatter.io/development/gm-proxy:1.5.0-dev`. Confirmed with @moosecanswim that we should keep that higher version.
