### ISSUE TITLE
Remove localhost and 0.0.0.0 from all cluster definitions.

### ISSUE THREAD

**Issue by joshua-rutherford** [greymatter-io/helm-charts#742]
`localhost` resolves to all of the loopback interfaces on the current machine.  in most cases this includes both `127.0.0.1` and `::1`.  as a result, when this is delivered to a sidecar, the sidecar provisions two instances for that cluster, one on each interface. unfortunately, unless the service bound to both explicitly or to all interfaces (i.e., 0.0.0.0 which must be avoided) half of the instances will always be unreachable.  This typically manifests in less than half the requests failing, but the exact percentage is based upon the number of retries and outlier detection.

further, clusters should never use `0.0.0.0` as the host.  i'm not really sure at all what this ultimately what happens with this but it is typically used to denote all interfaces when binding, but clusters are not used to bind so this must be a valid hostname or ip address.

**Comment by joshua-rutherford** [comment]
@danielpcox, @kaitmore, @justincely, @dontlaugh and @zoemccormick, for your awareness given you were all in this conversation.

**Comment by zakilur** [comment]
Cluster definitions have been changed to use `127.0.0.1`.
