### ISSUE TITLE
Define resources for Control, and all other GM services too

### ISSUE THREAD

**Issue by chrisbsmith** [greymatter-io/helm-charts#752]
We need to define resources for our services so we don't get stuck with any namespace defaults.  

In a customer environment, Control gets 128Mi of memory and it's hitting an OOM restarting the pod often

https://github.com/DecipherNow/helm-charts/blob/7dc075a70d6eade3322a9134b5ff4a955e4d2b65/fabric/control/values.yaml#L108

**Comment by rahug20** [comment]
Done!
https://github.com/greymatter-io/helm-charts/pull/775
