### ISSUE TITLE
edge configurable service type

### ISSUE THREAD

**Issue by zoemccormick** [greymatter-io/helm-charts#762]
based on environment, be able to configure the edge service type to loadbalancer without needing a patch

**Comment by chrisbsmith** [comment]
@zoemccormick can you explain this a bit more?  When would you want the service to be a load balancer vs clusterip

**Comment by zoemccormick** [comment]
@chrisbsmith we noticed in the eks quickstart installation that the AWS load balancer isn't correctly automatically created for the edge service https://github.com/DecipherNow/gm-gitbook-sync/issues/164, it seems like it may be useful to have it configurable. An alternative if we don't want to do this would be to keep documenting the patch step as a part of the process

**Comment by chrisbsmith** [comment]
Thanks @zoemccormick. This is probably worth documenting and supporting both models. Users can either define that Grey Matter handles all ingress traffic directly or they leverage the clusters ingress controller. 

We should have both models supported and documented in our official documentation

**Comment by chrisbsmith** [comment]
What I would like to avoid is customers paying for two ELBs unknowingly.

**Comment by zoemccormick** [comment]
Got it that makes sense, I will make a new issue in the gitbook repo for documenting this as well

**Comment by zoemccormick** [comment]
closed with #728 and #769
