### ISSUE TITLE
Installing Fabric causes Helm warnings

### ISSUE THREAD

**Issue by chrisbsmith** [greymatter-io/helm-charts#858]
When running `make fabric`, helm spews these warnings:

```console
"coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value <nil>"
```

While they're just warnings and the install proceeds, we should understand what is causing them and resolve it to remove the warnings from installation.

**Comment by moosecanswim** [comment]
Issue was due to the resources key not being defined in the control-api chart.  you can either put {} or the actual values but due to the note 

    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, and adjust them as necessary.

I just added the resources required
