### ISSUE TITLE
Mesh Redis failed to launch in OCP 4.6

### ISSUE THREAD

**Issue by chrisbsmith** [greymatter-io/helm-charts#859]
While a customer was deploying Grey Matter 1.3 into an OCP 4.6.9 cluster, he noticed that the `mesh-redis` pod failed to initialize. This is the error from the pod:

```console
Warning  Failed                  5m5s                  kubelet                  Error: container create failed: time="2021-01-20T17:37:10Z" level=error msg="container_linux.go:366: starting container process caused: exec: \"redis-server\": executable file not found in $PATH"
```

Investigation found we pass this command to the server: `redis-server --appendonly "yes"`.

Investigating with the customer found that if we removed the command from the STS, the pod started without issue because the image in use runs the `redis-server` command at launch.

The image in question is `centos/redis-32-centos7`

https://github.com/greymatter-io/helm-charts/blob/dfab70b9349025e6ba4199fdf9384064df82ebe8/fabric/redis/templates/redis.yaml#L43

If we do need to pass a command to the container, we should probably follow the `command` and `args` structure, as found here https://github.com/greymatter-io/helm-charts/blob/dfab70b9349025e6ba4199fdf9384064df82ebe8/fabric/jwt/values.yaml#L36-L41

**Comment by moosecanswim** [comment]
This may be taken care of in https://github.com/greymatter-io/helm-charts/pull/851 as @dgoldstein1 uses the `redis:3.2` image.

However i do like the idea of using command and args since that would put us more in line with best practices.

**Comment by dgoldstein1** [comment]
The bitnami appears to work ok in okd. Do you know why we’re using centos?

**Comment by dgoldstein1** [comment]
closed by https://github.com/greymatter-io/helm-charts/pull/851
