### ISSUE TITLE
Edge failed to create an OpenShift Route

### ISSUE THREAD

**Issue by chrisbsmith** [greymatter-io/helm-charts#861]
While working with a customer to deploy Grey Matter into an OCP 4.6.9 cluster, we noticed that the edge helm chart failed to create an OpenShift Route. Instead the customer had to manually create the cluster to allow ingress traffic.

When `environment` is set to `openshift`, we need to ensure that an OpenShift route is created for Edge.

**Comment by moosecanswim** [comment]
@chrisbsmith if you have access to the openshift cluster could you run an `oc get route edge -o yaml`?  That would be a quick way to see if the route apiVersion changed for oc 4.6.

**Comment by moosecanswim** [comment]
@chrisbsmith are you able to get the command history that lead to this?  

Were you using the docs install commands [here](https://docs.greymatter.io/installation/installation-kubernetes)  or was this a helm install using a branch/fork of our repo?

how did you set the environment to openshift? was it with a --set or changing up the globals.yaml ?

Were you using spire or not?

**I ran through this with a oc 4.6 and the route was created**

```
$ oc get route
NAME      HOST/PORT                                               PATH      SERVICES   PORT      TERMINATION   WILDCARD
edge      greymatter.console-openshift-console.apps-crc.testing             edge       proxy     passthrough   None
```
